function [ optimalMV,fval,exitflag,population,scores ] = mpc_wrapper_ga(yPastValues,uPastValues,dPastValues,...
                                          qMatrix,rMatrix,lambdaMatrix,beta,wMatrix,...
                                          yLims,uLims,lBounds,uBounds,...
                                          nTrees,nPredictors,na,nb,nc,...
                                          GAParameters)
%MPC_WRAPPER_GA Wrapper for GA optimization in Simulink
%   Detailed explanation goes here
%% GA Solver
objectiveFunction = @(x)mpc_lqr_function(x,beta,rMatrix, qMatrix, lambdaMatrix, wMatrix, yLims,uLims,...
                                      yPastValues, uPastValues, dPastValues,...
                                      nTrees, nPredictors, na, nb, nc);
outputFcn = @(options,state,flag)mpc_display_output_fcn(options,state,flag,...
                    qMatrix, beta, lambdaMatrix, wMatrix, yLims,uLims,...
                    yPastValues, uPastValues, dPastValues,...
                    nTrees, nPredictors, na, nb, nc);
options = optimoptions('ga','UseVectorized',true,'Display','off',...
                       'PopulationSize',GAParameters(1),...
                       'MaxGenerations',GAParameters(2),...
                       'MaxStallGenerations',GAParameters(3),...
                       'FunctionTolerance',GAParameters(4),...
                       'FitnessLimit',GAParameters(5),...
                       'EliteCount',GAParameters(6),...
                       'OutputFcn',[]...
                       );
[x,fval,exitflag,output,population,scores] = ga(objectiveFunction,GAParameters(end),[],[],[],[],lBounds,uBounds,[],options);
%% Saturation of MV
[m,~] = size(rMatrix);
% Saturation of MV
uLowLims = uLims(:,1,1);
uHighLims = uLims(:,1,2);
uPossible = x(1:m)'+uPastValues(:,1);
optimalMV = mpc_saturate_mv(uPossible,[uLowLims uHighLims]);
end

