function [ optimalMV ] = mpc_wrapper_ga(yPastValues,uPastValues,dPastValues,...
                                          qMatrix,rMatrix,lambdaMatrix,beta,wMatrix,...
                                          yLims,lBounds,uBounds,nVars,...
                                          nTrees,nPredictors,na,nb,nc,...
                                          nPopulation,maxGens,maxStallGens)
%MPC_WRAPPER_GA Wrapper for GA optimization in Simulink
%   Detailed explanation goes here
objectiveFunction = @(x)mpc_lqr_function(x,beta,rMatrix, qMatrix, lambdaMatrix, wMatrix, yLims,...
                                      yPastValues, uPastValues, dPastValues,...
                                      nTrees, nPredictors, na, nb, nc);
options = optimoptions('ga','UseVectorized',true,'Display','off',...
                       'MaxStallGenerations',maxStallGens,...
                       'PopulationSize',nPopulation,'MaxGenerations',maxGens);
[x,fval,exitflag,output,population,scores] = ga(objectiveFunction,nVars,[],[],[],[],lBounds,uBounds,[],options);
optimalMV = x(4:6); % Change after
end

