function [ optimalMV ] = mpc_wrapper_ga(yPastValues,uPastValues,dPastValues,...
                                          qMatrix,rMatrix,lambdaMatrix,beta,wMatrix,...
                                          yLims,lBounds,uBounds,nVars,...
                                          nTrees,nPredictors,na,nb,nc)
%MPC_WRAPPER_GA Wrapper for GA optimization in Simulink
%   Detailed explanation goes here
objectiveFunction = @(x)mpc_lqr_function(x,beta,rMatrix);
nonlinearConstraintsFunction = @(x)mpc_constraint_generator(x,qMatrix,lambdaMatrix,wMatrix,yLims,...
                                              yPastValues,uPastValues,dPastValues,...
                                              nTrees,nPredictors,...
                                              na,nb,nc);
options = optimoptions('ga','UseVectorized',true,'Display','off','MaxStallGenerations',500,'PopulationSize',100,'MaxGenerations',5);
[x,fval,exitflag,output,population,scores] = ga(objectiveFunction,nVars,[],[],[],[],lBounds,uBounds,nonlinearConstraintsFunction,options);
optimalMV = x(4:6); % Change after
end

